// Autogenerated Class (Header File)
// Author : G.Gavalian
// Date   : Mon Jul  9 16:57:07 EDT 2007
//

#ifndef __TCTOperations__
#define __TCTOperations__
#include <iostream>
#include <TROOT.h>
#include <TVector3.h>
#include <TObject.h>
#include <TLorentzVector.h>

class TCTOperations : public TObject {

private:

public:

TCTOperations ();
~TCTOperations ();


 TLorentzVector  GetOperV(const char *oper, TLorentzVector *v1);
 Double_t        GetOper(const char *oper, TLorentzVector *v1);

 TLorentzVector  func_v_summ_lvect(    TLorentzVector v1,TLorentzVector v2){return v1+v2;};
 TLorentzVector  func_v_subs_lvect(    TLorentzVector v1,TLorentzVector v2){return v1-v2;};
 TLorentzVector  func_v_boost_lvect(   TLorentzVector v1,TLorentzVector v2);
 TLorentzVector  func_v_unboost_lvect( TLorentzVector v1,TLorentzVector v2);
 TLorentzVector  func_v_unboost_lvect_dir( TLorentzVector v1,TLorentzVector v2, TLorentzVector v3);
 TVector3        func_ray_intersect( TVector3 v1, TVector3 p1, 
				     TVector3 v2, TVector3 p2, Double_t *dist ) ;

ClassDef(TCTOperations,1)


};
#endif
