// Autogenerated Class (Source File)
// Author : G.Gavalian
// Date   : Tue Jul 10 15:25:05 EDT 2007
//

#include "TCTTextReader.h"



ClassImp(TCTTextReader)


TCTTextReader::TCTTextReader (){

}

TCTTextReader::~TCTTextReader (){

}

//-----------------
//-----------------
//-----------------
void   TCTTextReader::Open(const char *fname)
{
  ifs.open (fname);
}

int    TCTTextReader::Next()
{
  if(!ifs.eof()){
    getline(ifs,str_line);
    return 1;
  } else return -1;
}
void   TCTTextReader::Close()
{
  ifs.close();
  ifs.clear();
}

double    TCTTextReader::GetNumber(int n)
{
 double  val;
 istringstream istr;
 istr.str(str_line);
 for(int i=0;i<n+1;i++) istr >> val;
 return val;
}

TVector3  TCTTextReader::GetVect(int start)
{
  TVector3 v;
  double a1 = GetNumber(start);
  double a2 = GetNumber(start+1);
  double a3 = GetNumber(start+2);
  //  printf("GetVect: %f %f %f\n",a1,a2,a3);
  v.SetXYZ(a1,a2,a3);
  return v;
}
