C----------------------------------------------------------------------
C-
C-   Created  6-MAY-1996   Stepan Stepanyan, CEBAF
C-
C----------------------------------------------------------------------
C
C ****  COMMON LEPTOU  Lepto program common block
C
      REAL    cut
      REAL    parl
      REAL    x
      REAL    y
      REAL    w2
      REAL    q2
      REAL    u
      INTEGER lst
      COMMON /leptou/ cut(14),lst(40),parl(30),x,y,w2,q2,u
