sudo: required
language: cpp
services:
- docker
script:
- mkdir parms
- docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
- docker build -t tylern4/clas6 .
- docker images -a
- docker push tylern4/clas6
