// Autogenerated Class (Header File)
// Author : G.Gavalian
// Date   : Sun Apr  1 20:42:16 EDT 2007
//

#ifndef __TCTStringUtils__
#define __TCTStringUtils__
#include <iostream>
#include <TROOT.h>
#include <TVector3.h>
#include <TObject.h>
#include <TString.h>

class TCTStringUtils {
private:
  char  cbuff[128];

public:
TCTStringUtils ();
~TCTStringUtils ();

  TString   PullStr(TString *fstr, const char c = ' ');
  void      PushStr(TString pstr, TString *fstr, const char c = ' ');
  int       GetCount(TString _astr,char __crt);
  TString   GetSubstring(TString  a, int start , int len);
  
};
#endif
