      REAL sigmaT(2),sigmaL(2),sigmaTT(2),sigmaTL(2),sigma(2),
     +sigmaTLP(2),sigmaTy(2),sigmaLy(2),sigmaTTx(2),sigmaTTy(2),
     +sigmaTTz(2),sigmaTLx(2),sigmaTLy(2),sigmaTLz(2),
     +sigmaTTPx(2),sigmaTTPz(2),sigmaTLPx(2),sigmaTLPy(2),sigmaTLPz(2),
     +robs(10,2)

      common/res_func/sigmaT,sigmaL,sigmaTT,sigmaTL,sigma,
     +sigmaTLP,sigmaTy,sigmaLy,sigmaTTx,sigmaTTy,
     +sigmaTTz,sigmaTLx,sigmaTLy,sigmaTLz,
     +sigmaTTPx,sigmaTTPz,sigmaTLPx,sigmaTLPy,sigmaTLPz,
     +robs
