c
c    all moments
c
      real hs1Itpcos,hs1Itpsin,hc1Itpcos
     6               ,hc1Itpsin, hc0Itpcos,hc0Itpsin
      common/momentstpI/hs1Itpcos,hs1Itpsin,hc1Itpcos
     6               ,hc1Itpsin,hc0Itpcos,hc0Itpsin
c
      real hc0dvcs,hc1dvcs,hs1dvcs,hs2dvcs
      common/momentsDVCS/hc0dvcs,hc1dvcs,hs1dvcs,hs2dvcs
c
      real hc0BH,hc1BH,hc2BH,hc0BHlp,hc1BHlp
     6,hc0BHtpcos,hc1BHtpcos,hs1BHtpsin
      common/momentsBH/hc0BH,hc1BH,hc2BH,hc0BHlp,hc1BHlp
     6,hc0BHtpcos,hc1BHtpcos,hs1BHtpsin
c
      real hs1Ilp,hc1Ilp,hc0Ilp
      common/momentslpI/hs1Ilp,hc1Ilp,hc0Ilp
c
      real hs1Iunp,hc1Iunp,hc0Iunp,hs2Iunp,hc2Iunp
      common/momentsunpI/hs1Iunp,hc1Iunp,hc0Iunp,hs2Iunp,hc2Iunp







