#ifndef __ALL_ROOT_HEADER_H
#define __ALL_ROOT_HEADER_H

#include <stdio.h>
#include <stdlib.h>
#include <iostream>
#include <sstream>
#include <cmath>
#include <Hoption.h>
#include <Hparam.h>
#include <TMath.h>
#include <TApplication.h>
#include <TButton.h>
#include <TCanvas.h>
#include <TControlBar.h>
#include <TDialogCanvas.h>
#include <TDirectory.h>
#include <TEnv.h>
#include <TF1.h>
#include <TF2.h>
#include <TFile.h>
#include <TCutG.h>
#include <TFrame.h>
#include <TGaxis.h>
#include <TGButton.h>
#include <TGButtonGroup.h>
#include <TGCanvas.h>
#include <TGClient.h>
#include <TGComboBox.h>
#include <TGDoubleSlider.h>
#include <TGFileDialog.h>
#include <TGFrame.h>
#include <TGIcon.h>
#include <TGImageMap.h>
#include <TGLabel.h>
#include <TGListBox.h>
#include <TGMenu.h>
#include <TGMsgBox.h>
#include <TGNumberEntry.h>
#include <TGProgressBar.h>
#include <TGShutter.h>
#include <TGSlider.h>
#include <TGTab.h>
#include <TGTextEdit.h>
#include <TGTextEntry.h>
#include <TGraph.h>
#include <TGraphErrors.h>
#include <TH1.h>
#include <TH2.h>
#include <THistPainter.h>
#include <TLatex.h>
#include <TLine.h>
#include <TMarker.h>
#include <TPad.h>
// #include <TPadView3D.h>
#include <TPaveLabel.h>
#include <TROOT.h>
#include <TRandom.h>
#include <TRint.h>
#include <TRootEmbeddedCanvas.h>
#include <TSocket.h>
#include <TSQLResult.h>
#include <TSQLRow.h>
#include <TSQLServer.h>
#include <TStyle.h>
#include <TSysEvtHandler.h>
#include <TSystem.h>
#include <TTimer.h>
#include <TVector.h>
#include <TView.h>
#include <TVirtualPS.h>
#include <TVirtualX.h>

#ifndef USE_OLD_ROOTVERSION
#include <TGColorSelect.h>
#endif
#include "jdefine.h"

#endif
