// Autogenerated Class (Header File)
// Author : G.Gavalian
// Date   : Tue Mar 27 12:58:44 EST 2007
//

#ifndef __TCTEventSelector__
#define __TCTEventSelector__
#include <iostream>
#include <TROOT.h>
#include <TVector3.h>
#include <TObject.h>
#include <TCTParticle.h>
#include <TCTCompositeParticle.h>
#include <TCTPhotonSelector.h>
#include <TCTVector.h>
#include <TCTVariable.h>
#include <TNtuple.h>
#include <TArrayF.h>
#include "TCTStringUtils.h"
#include "TCTTextReader.h"
#include "TDSTReader.h"
#include "TDatabasePDG.h"
#include "TParticlePDG.h"

#define MAX_REACT_PART     2
#define MAX_PRODUCT_PART   10


typedef  struct {
  int     lund_id;
  string  name;
  double  mass;
} TReactionParticle_t;


class TCTEventSelector {

private:

  TNtuple    *fNT;
  char       fLineBuffer[4096];
  TObjArray  *fPartArray;
  TObjArray  *fCompositePartArray;
  Int_t       fInteRactionVertex_Indx;
  
  TObjArray  *fVectArray;
  TObjArray  *fVarArray;

  TString     fReaction;
  TString     fProducts;

  TVirtualReader   *fReader;

  Int_t           fNReactionParticles;
  TLorentzVector  vl_React[MAX_REACT_PART];
  TLorentzVector  vl_Products[MAX_PRODUCT_PART];
  TReactionParticle_t   fParticleList[MAX_PRODUCT_PART];
  TDatabasePDG   fPDGData;
  TCTPhotonSelector   fPhotonSel;

public:

TCTEventSelector ();
~TCTEventSelector ();

 void  InitNtuple();
 void  FillNtuple();
 void  GetNtupleBuff(TArrayF *fbuff);

 void  AddParticle(const char *name, int type, double mass);
 void  AddCompositeParticle(const char *name, int p1, int p2, double __mass, double pid_cut=0.020);
 void  AddCompositeParticle(const char *name, const char *__fop, double __mass, double pid_cut=0.020);
 void  AddVector(const char *name,TLorentzVector v);
 void  AddVector(const char *name,const char *part);
 void  AddVector(const char *name,const char *oper, int nop, TString *sarr);

 void  AddVariable(Int_t  Type,const char *name,const char *sys_name,const char *sys_var);
 void  AddVariable(const char *name,const char *oper,const char *var1,const char *var2);
 void  AddVariable(const char *name,double value);

 TVector3  GetInterVertex();

 void  FillVariables();
 void  SetInteractionVertex(int idx){fInteRactionVertex_Indx = idx;};

 void  SetReaction(const char *react, const char *products);
 void  SetReader(TVirtualReader  *fR){fReader = fR;fPhotonSel.SetDSTReader(fReader);};
 int    AnalyseEvent();
 void   ConstructComposite();
 int    Pattern(const char *__str_pat, int excl_flag_ch = -1, int excl_flag_neutral = -1);

 TCTParticle            *GetParticle(int idx);
 TCTCompositeParticle   *GetCompositeParticle(int idx);

 TLorentzVector  GetLorentzVector(const char *partname);

 TString   GetBranchList();

 double    GetVariable(const char *name);
 // void  AddVariable(const char *name,const char *vec_name,const char *vec_var);
 void      ExecCommand(const char *sys,const char *cmd, const char *args);
 TString   GetVarBuffer();

 void     SetVar(const char *name,double val);
 void     SetVect(const char *name,TLorentzVector vl);

 void     LoadConfig(const char *fname);
 void     Fill();
 void     PrintPart();
 void     PrintVect(int flag=0);
 void     PrintVars();
 
};
#endif
