// Autogenerated Class (Source File)
// Author : G.Gavalian
// Date   : Tue Mar 27 13:21:19 EST 2007
//

#include "TCTParticle.h"

ClassImp(TCTParticle)


TCTParticle::TCTParticle (const char *name){
  fPartState     = 0;
  fExclusiveFlag = 0;
  SetName(name);
}

TCTParticle::TCTParticle (const char *name,int type,double mass){
  fPartState     = 0;
  fExclusiveFlag = 0;
  fPartState     = 0;
  fExclusiveFlag = 0;
  SetPartType (type);
  SetMass(mass);
  SetName(name);
}

TCTParticle::~TCTParticle (){

}

//-----------------
//-----------------
//-----------------
void   TCTParticle::ResetPart()
{
  fPartStatus = 0;
  fPartVertex.SetXYZ(0.,0.,0.);
  fPartLorentzVector.SetPxPyPzE(0.,0.,0.,0.);
}


int    TCTParticle::SetParticle(TVirtualReader *fR, int idx)
{
  if(fPartStatus==1) return -1;
  if(fR->GetPartID(idx)==fPartType){
    fPartLorentzVector.SetVectM(fR->GetPart3Vector(idx),fPartMass);
    fPartVertex = fR->GetPartVertex(idx);
    fPartStatus = 1;
  }
  if(fPartStatus!=1) return -1;
  return 1;
}
int    TCTParticle::SetPart(TEVNTClass *ptr)
{
  if(fPartStatus==1) return -1;

  if(ptr->GetId()==fPartType){
    //    printf("aaaaaa %f\n",fPARTBank.GetMomVec().Mag());
    TEVNTClass  tmp_evt(ptr);
    fPARTBank   = tmp_evt;
    fPartLorentzVector.SetVectM(fPARTBank.GetMomVec(),fPartMass);
    fPartVertex.SetXYZ(tmp_evt.X,tmp_evt.Y,tmp_evt.Z);
    fPartStatus++;
  }

  if(fPartStatus==0) return -1;
  return 1;
}

Double_t        TCTParticle::Get(const char *var)
{
  TString  str_var(var);
  double   var_d = 0.;
  if(str_var.CompareTo("Px")==0) var_d = fPartLorentzVector.Px();
  if(str_var.CompareTo("P")==0) var_d = fPartLorentzVector.P();
  if(str_var.CompareTo("Py")==0) var_d = fPartLorentzVector.Py();
  if(str_var.CompareTo("Pz")==0) var_d = fPartLorentzVector.Pz();
  if(str_var.CompareTo("Beta")==0) var_d = fPARTBank.GetBeta();
  if(str_var.CompareTo("Charge")==0) var_d = fPARTBank.GetCharge();
  if(str_var.CompareTo("Vx")==0) var_d = fPARTBank.GetX();
  if(str_var.CompareTo("Vy")==0) var_d = fPARTBank.GetY();
  if(str_var.CompareTo("Vz")==0) var_d = fPARTBank.GetZ();
  //  if(str_var.CompareTo("Vy")) var_d = fPARTBank.GetPx();
  return  var_d;
}

TLorentzVector  TCTParticle::GetV()
{
  TLorentzVector v;
  v.SetPxPyPzE(0.,0.,0.,0.);
  v = fPartLorentzVector;
  return v;
}
