// Autogenerated Class (Header File)
// Author : G.Gavalian
// Date   : Tue Mar 27 16:46:05 EST 2007
//

#ifndef __TCTVariable__
#define __TCTVariable__
#include <iostream>
#include <TROOT.h>
#include <TVector3.h>
#include <TObject.h>

#define CTVAR_STATIC     81
#define CTVAR_PARTICLE   82
#define CTVAR_VECTOR     83
#define CTVAR_VARIABLE   84
#define CTVAR_VECTOR_OP  85


class TCTVariable : public TNamed {

private:

  Int_t    fVarType;
  Double_t fVarValue;
  Double_t fCutValue_Low;
  Double_t fCutValue_High;


  TString  fSystemName;
  TString  fSystemVar;
  TString  fOperation;

  TString  fOperand_1;
  TString  fOperand_2;
  

public:

  TCTVariable (const char *name, double value);
  TCTVariable (const char *name, const char *sys_name, const char *sys_var, int type=CTVAR_PARTICLE);
  TCTVariable (const char *name, const char *oper, const char *var_1, const char *var_2);
  
  void  Fill(TObjArray *farr, const char *system);
  
  ~TCTVariable ();

  Int_t     GetType(){return fVarType;};
  Double_t  Get(){return fVarValue;};
  TString   GetSystemName(){return fSystemName;};
  TString   GetSystemVar(){return fSystemVar;};
  Int_t     GetStatus();
  Int_t     SetCuts(double __low, double __high);
  void      GetCuts(double *__lo,double *__hi){*__lo = fCutValue_Low;*__hi = fCutValue_High;};
  void      Set(double val){fVarValue = val;};
  void      Print();
  void      DoOperation(double v1,double v2);


  ClassDef(TCTVariable,1)
    
};
#endif
