// Autogenerated Class (Header File)
// Author : G.Gavalian
// Date   : Wed Jun 27 16:16:24 EDT 2007
//

#ifndef __TNtHisto__
#define __TNtHisto__
#include <iostream>
#include <TROOT.h>
#include <TVector3.h>
#include <TObject.h>
#include <TNamed.h>
#include <TTree.h>


class TNtHisto : public TNamed {

private:


public:

  TString    fCutsString;
  TString    fEpsFileName;
  TString    fVariable;


TNtHisto (const char *hname);
~TNtHisto ();

 virtual  int    GetDim();
 virtual  void   SetTitle(const char *title, const char *ytit="");
 virtual  void   Fill(TTree *tree, const char *opt = "goff");
 virtual  void   Print();
 virtual  TObject *GetH();

 void  SetCuts( const char *cuts)      {   fCutsString = cuts;   };
 void  SetEpsName(const char *en)      {   fEpsFileName = en;    };
 void  ClearCuts()                     {   fCutsString = "";     };
 void  AppendCut(const char *cut)      {   fCutsString += "&&"; 
                                           fCutsString += cut;   };
 void  SetVar(  const char *var)       {   fVariable    = var;   };

 TString    GetEpsName()               {   return fEpsFileName;  };
 TString    GetVar()                   {   return fVariable;     };
 TString    GetCuts()                  {   return fCutsString;   };
 virtual    TString    GetHistName();
 virtual    void       SetBins(int nx, double xmin, double xmax, int ny = 0, double ymin = 0., double ymax=0.);

 ClassDef(TNtHisto,1)

};
#endif
