// Autogenerated Class (Source File)
// Author : G.Gavalian
// Date   : Wed Jun 27 16:16:24 EDT 2007
//

#include "TNtHisto.h"


ClassImp(TNtHisto)

TNtHisto::TNtHisto (const char *hname){
  SetName(hname);
}

TNtHisto::~TNtHisto (){

}

//-----------------
//-----------------
//-----------------
int    TNtHisto::GetDim()
{
  return 0;
}

void   TNtHisto::SetTitle(const char *title, const char *ytit){};
void   TNtHisto::Fill(TTree *tree, const char *opt){};
void   TNtHisto::Print()
{
  printf("BASE CLASS:===>>\n");
}

TObject *TNtHisto::GetH(){return NULL;}


TString    TNtHisto::GetHistName()
{
  TString  hist_name = "_hist_0d_";
  hist_name += GetName();
  return hist_name;
}

void       TNtHisto::SetBins(int nx, double xmin, double xmax, int ny, double ymin, double ymax){

}
