// Autogenerated Class (Header File)
// Author : G.Gavalian
// Date   : Tue Nov  6 15:17:46 EST 2007
//

#ifndef __TCTCompositeParticle__
#define __TCTCompositeParticle__
#include <iostream>
#include <cmath>
#include <TROOT.h>
#include <TVector3.h>
#include <TObject.h>
#include "TCTGenParticle.h"

class TCTCompositeParticle : public TCTGenParticle {

private:

 TString         fOperator;
 Double_t        fPartMassCut;

public:


TCTCompositeParticle (const char *__pname,const char *__foperator, double __mass,double pid_cut);

~TCTCompositeParticle ();

 Int_t    GetNPart();
 Int_t    GetPart(int __indx);
 Int_t    GetSign(int __indx);

 TString  GetOperator(){return fOperator;};
 void     Construct(TCTGenParticle **fPartBuff, Int_t n_part);
 void     Construct(TCTGenParticle  *fPartBuff, Int_t n_part);
 void     Construct(TLorentzVector  *fvbuff, TVector3 *fzbuff, Int_t n_part);

 void     SetOperator(const char *oper){fOperator = oper;};
 void     Print();

ClassDef(TCTCompositeParticle,1)


};
#endif
