// Autogenerated Class (Header File)
// Author : G.Gavalian
// Date   : Tue Mar 25 17:24:13 EDT 2008
//

#ifndef __TCTHistoContainer__
#define __TCTHistoContainer__
#include <iostream>
#include <TROOT.h>
#include <TVector3.h>
#include <TObject.h>
#include "TNtHisto.h"
#include "TNtHisto1D.h"
#include "TNtHisto2D.h"
#include <TObjArray.h>
#include <TFile.h>
#include <TNtuple.h>
#include <vector>
#include <string>
#include <TXMLEngine.h>

using namespace std;

class TCTHistoContainer : public TObject {

private:

  TObjArray  *fHistArray;
  TNtuple    *fNtuple;
  TXMLEngine    fXMLEngine;
public:

TCTHistoContainer ();
~TCTHistoContainer ();

 void   AddHist(const char *_name, const char *_title, int _nbins, double _x_min,double _x_max, const char *_var, const char *_cuts);

 void   SetStyle(TH1D *h1,int _style = 1);
 void   AddHist(TNtHisto *_fh);

 void   SaveToFile(const char *_fname);
 void   SaveToDir(const char *pattern);

 void   SetNtuple(TNtuple *_fNt) {fNtuple = _fNt;};
 void   Draw(const char *_histname);
 void   DrawAll();
 void   Fill(const char *_histname);

 vector<string>  GetHistNames();
 
 TNtHisto   *GetHistByName(const char *_hname);
 TNtHisto   *GetHistByIndex(int _indx);

 void        LoadConfig(const char *_xml_file);
 void        _XML_Load1dHist(XMLNodePointer_t node);
 void        _XML_Load2dHist(XMLNodePointer_t node);
 

 Int_t   GetNHistos(){return fHistArray->GetEntries();};
 void    Print();

ClassDef(TCTHistoContainer,1)


};
#endif
