// Autogenerated Class (Source File)
// Author : G.Gavalian
// Date   : Tue Dec 18 14:35:05 EST 2007
//

#include "TCTInputArguments.h"



ClassImp(TCTInputArguments)


TCTInputArguments::TCTInputArguments (){
  fArgString = new TOrdCollection(5);
}

TCTInputArguments::~TCTInputArguments ()
{

}

//-----------------
//-----------------
//-----------------
void     TCTInputArguments::AddString(const char *__str)
{
  fArgString->AddLast(new TObjString(__str));
}
//---------------------------------------------------------------
TString  TCTInputArguments::GetString()
{
  TString  _aa;
  int in_arr = fArgString->GetEntries();
  for(int i=0;i<in_arr;i++){
    TObjString *ptr = (TObjString *) fArgString->At(i);
    if(ptr!=NULL){
      _aa += ptr->GetString();
      _aa += " ";
    }
  }
  return _aa;
}
Int_t     TCTInputArguments::FindObject(const char *__str)
{
  TString _aa;
  int in_arr = fArgString->GetEntries();
  for(int i=0;i<in_arr;i++){
    TObjString *ptr = (TObjString *) fArgString->At(i);
    if(ptr!=NULL){
      _aa = ptr->GetString(); 
      if(_aa.CompareTo(__str)==0) return i;
    }
  }
  return -1;
}
//---------------------------------------------------------------
TString  TCTInputArguments::GetOption(const char *__opt)
{
  TString  _aa = "";
  int _idx = FindObject(__opt);
  if(_idx>=0&&(_idx+1)<GetNArgs()){
    TObjString *ptr = (TObjString *) fArgString->At(_idx+1);
    if(ptr!=NULL){
      _aa = ptr->GetString();
      fArgString->RemoveAt(_idx+1);
      fArgString->RemoveAt(_idx);
    }
  }
  return _aa;
}
//---------------------------------------------------------------
Int_t    TCTInputArguments::GetNArgs()
{
  return  fArgString->GetEntries();
}
//---------------------------------------------------------------
TString    TCTInputArguments::GetArg(int _idx)
{
  TString aa="";
  TObjString *ptr = (TObjString *) fArgString->At(_idx); 
  if(ptr!=NULL) aa = ptr->GetString();
  return aa;
}
