// Autogenerated Class (Source File)
// Author : G.Gavalian
// Date   : Thu Dec  6 13:51:26 EST 2007
//

#include "TCTParticleID.h"



ClassImp(TCTParticleID)


TCTParticleID::TCTParticleID (){

}

TCTParticleID::~TCTParticleID (){

}

//-----------------
//-----------------
//-----------------
