// Autogenerated Class (Header File)
// Author : G.Gavalian
// Date   : Thu Dec  6 13:51:26 EST 2007
//

#ifndef __TCTParticleID__
#define __TCTParticleID__
#include <iostream>
#include <TROOT.h>
#include <TVector3.h>
#include <TObject.h>
#include <TCTParticle.h>
#include <TCTCompositeParticle.h>
#include <TCTPhotonSelector.h>
#include <TCTVector.h>
#include <TCTVariable.h>
#include <TNtuple.h>
#include <TArrayF.h>
#include "TCTStringUtils.h"
#include "TCTTextReader.h"
#include "TDSTReader.h"
#include "TDatabasePDG.h"
#include "TParticlePDG.h"
#include "TCTOperations.h"

class TCTParticleID : public TObject {

private:

  TVirtualReader  *fReader;

public:

TCTParticleID ();
~TCTParticleID ();

 void       DoParticleId();
 Int_t      GetNPart();
 TVector3   GetBeamVector();
 TVector3   GetTargetVector();
 TVector3   GetParticleVector(int _idx);
 Double_t   GetParam(const char *_parname);
 Int_t      GetParticleID(int _idx);
 void       SetReader(TVirtualReader *_fExtReader){fReader = _fExtReader;}
 

ClassDef(TCTParticleID,1)

};
#endif
