// Autogenerated Class (Header File)
// Author : G.Gavalian
// Date   : Fri Mar 30 14:33:33 EST 2007
//

#ifndef __TFrameTitle__
#define __TFrameTitle__
#include <iostream>
#include <TROOT.h>
#include <TVector3.h>
#include <TObject.h>
#include <TSystem.h>
#include <TGButton.h>
#include <TGLabel.h>
#include <TGPicture.h>
#include <TGIcon.h>
#include <TGResourcePool.h>


class TFrameTitle :  public TGCompositeFrame {
private:
    TGLabel *fTextLabel1;
    TGGC fTextGC;
public:
TFrameTitle (const TGWindow *p,
              const Text_t *mainText);

~TFrameTitle ();


ClassDef(TFrameTitle,1)


};
#endif
