// Autogenerated Class (Header File)
// Author : G.Gavalian
// Date   : Fri Mar 30 10:29:03 EST 2007
//

#ifndef __TFrameNtUtuls__
#define __TFrameNtUtuls__
#include <iostream>
#include <TROOT.h>
#include <TVector3.h>
#include <TObject.h>
#ifndef ROOT_TGFrame
#include "TGFrame.h"
#endif
#include <TGSlider.h>
#ifndef ROOT_TGButton
#include "TGButton.h"
#endif

#ifndef ROOT_TGTextEntry
#include "TGTextEntry.h"
#endif

#ifndef ROOT_TGListBox
#include <TGListBox.h>
#endif

#ifndef ROOT_TGTab
#include <TGTab.h>
#endif
#include <TGButton.h>
#include <TGFileDialog.h>
#include "TCTParticleList.h"
#include <TGNumberEntry.h>

//extern TGuiStudio *gGuiStudio;


class TFrameContainer :  public TGCompositeFrame {

private:

  TGNumberEntry *fNEventsRun;
  TGLayoutHints *fButtonLayout;
  TGLayoutHints *fListLayout;

  TGButton *fAddCutButton;

  TGButton *fRunButton;
  TGButton *fEditButton;
  TGButton *fDrawButton;

  TGButton *fEditCutButton;

  TGButton *fAddHistButton;
  TGButton *fEditHistButton;
  TGButton *fDrawHistButton;
  TGButton *fDrawSameButton;
  TGButton *fDrawHistAllButton;

  TGButton *fLoadConfButton;
  TGButton *fSaveConfButton;
  TGButton *fSaveFileButton;

  TGHSlider           *fNEvtSlider;
  TGListBox           *fListBoxCuts;
  TGListBox           *fListBoxHistos;

  //  TNtUtils            *fNtUtil;


  TString  fCurrentFigureName;


  TGCompositeFrame   *fSelectionFrame;
  TGCanvas           *fTreeView;
  TCTParticleList    *fParticleList;


  void   _cmd_Run();
  void   _cmd_Draw();


public:

  TFrameContainer (const TGWindow* p,
		 TGWindow* buttonHandler, Int_t  drawEventID, Int_t  addcutEventId, Int_t  addhistEventId);

~TFrameContainer ();


 virtual Bool_t   ProcessMessage(Long_t msg, Long_t parm1, Long_t parm2);

 void    LoadConfigFile(int status = 1);
 void    SaveConfigFile();
 void    DrawHisto(const char *opt="");
 void    DrawHistoAll();
 void    SaveFile(const char *filename);

 void    SetSliderRange(int _min, int _max, int _pos = 0);

 void    OpenProject(const char *filename);
 
 void    Init(const char *ntname,const char *file);
 void    UpdateFrame(TCTContainer *_fct);

 void   _cmd_ChangeNEvents();
 TString  GetFigureName(){return fCurrentFigureName;};


ClassDef(TFrameContainer,1)


};
#endif
