/********************************************************************
* TGuiStudioDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error TGuiStudioDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#include "G__ci.h"
extern "C" {
extern void G__cpp_setup_tagtableTGuiStudioDict();
extern void G__cpp_setup_inheritanceTGuiStudioDict();
extern void G__cpp_setup_typetableTGuiStudioDict();
extern void G__cpp_setup_memvarTGuiStudioDict();
extern void G__cpp_setup_globalTGuiStudioDict();
extern void G__cpp_setup_memfuncTGuiStudioDict();
extern void G__cpp_setup_funcTGuiStudioDict();
extern void G__set_cpp_environmentTGuiStudioDict();
}


#include "TROOT.h"
#include "TMemberInspector.h"
#include "TGuiStudio.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__TGuiStudioDictLN_TClass;
extern G__linked_taginfo G__TGuiStudioDictLN_TBuffer;
extern G__linked_taginfo G__TGuiStudioDictLN_TMemberInspector;
extern G__linked_taginfo G__TGuiStudioDictLN_TObject;
extern G__linked_taginfo G__TGuiStudioDictLN_vectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgR;
extern G__linked_taginfo G__TGuiStudioDictLN_vectorlETStreamerInfomUcOallocatorlETStreamerInfomUgRsPgR;
extern G__linked_taginfo G__TGuiStudioDictLN_reverse_iteratorlEvectorlETStreamerInfomUcOallocatorlETStreamerInfomUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TGuiStudioDictLN_maplEvoidmUcOshortcOlesslEvoidmUgRcOallocatorlEpairlEvoidmUsPconstcOshortgRsPgRsPgR;
extern G__linked_taginfo G__TGuiStudioDictLN_TMatrixTBaselEfloatgR;
extern G__linked_taginfo G__TGuiStudioDictLN_TMatrixTBaselEdoublegR;
extern G__linked_taginfo G__TGuiStudioDictLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__TGuiStudioDictLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__TGuiStudioDictLN_TElementActionTlEfloatgR;
extern G__linked_taginfo G__TGuiStudioDictLN_TElementPosActionTlEfloatgR;
extern G__linked_taginfo G__TGuiStudioDictLN_TMatrixTlEfloatgR;
extern G__linked_taginfo G__TGuiStudioDictLN_TMatrixTRow_constlEfloatgR;
extern G__linked_taginfo G__TGuiStudioDictLN_TMatrixTRowlEfloatgR;
extern G__linked_taginfo G__TGuiStudioDictLN_TMatrixTDiag_constlEfloatgR;
extern G__linked_taginfo G__TGuiStudioDictLN_TMatrixTColumn_constlEfloatgR;
extern G__linked_taginfo G__TGuiStudioDictLN_TMatrixTFlat_constlEfloatgR;
extern G__linked_taginfo G__TGuiStudioDictLN_TMatrixTSub_constlEfloatgR;
extern G__linked_taginfo G__TGuiStudioDictLN_TMatrixTSparseRow_constlEfloatgR;
extern G__linked_taginfo G__TGuiStudioDictLN_TMatrixTSparseDiag_constlEfloatgR;
extern G__linked_taginfo G__TGuiStudioDictLN_TMatrixTColumnlEfloatgR;
extern G__linked_taginfo G__TGuiStudioDictLN_TMatrixTDiaglEfloatgR;
extern G__linked_taginfo G__TGuiStudioDictLN_TMatrixTFlatlEfloatgR;
extern G__linked_taginfo G__TGuiStudioDictLN_TMatrixTSublEfloatgR;
extern G__linked_taginfo G__TGuiStudioDictLN_TMatrixTSparseRowlEfloatgR;
extern G__linked_taginfo G__TGuiStudioDictLN_TMatrixTSparseDiaglEfloatgR;
extern G__linked_taginfo G__TGuiStudioDictLN_TGObject;
extern G__linked_taginfo G__TGuiStudioDictLN_TGWindow;
extern G__linked_taginfo G__TGuiStudioDictLN_TQObject;
extern G__linked_taginfo G__TGuiStudioDictLN_TGFrame;
extern G__linked_taginfo G__TGuiStudioDictLN_TGCompositeFrame;
extern G__linked_taginfo G__TGuiStudioDictLN_TGMainFrame;
extern G__linked_taginfo G__TGuiStudioDictLN_TFrameNtUtuls;
extern G__linked_taginfo G__TGuiStudioDictLN_vectorlETStringcOallocatorlETStringgRsPgR;
extern G__linked_taginfo G__TGuiStudioDictLN_reverse_iteratorlEvectorlETStringcOallocatorlETStringgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TGuiStudioDictLN_TFrameTitle;
extern G__linked_taginfo G__TGuiStudioDictLN_TGPopupMenu;
extern G__linked_taginfo G__TGuiStudioDictLN_TFrameTabView;
extern G__linked_taginfo G__TGuiStudioDictLN_TGStatusBar;
extern G__linked_taginfo G__TGuiStudioDictLN_TGMenuBar;
extern G__linked_taginfo G__TGuiStudioDictLN_TGuiStudio;

/* STUB derived class for protected member access */
