//________________________________________________________
// Autogenerated Class (Header File)
// Author : G.Gavalian
// Date   : Thu Mar 29 11:19:03 EST 2007
//
//_________________________________________________________


#ifndef __TNtHisto1D__
#define __TNtHisto1D__
#include <iostream>
#include <TROOT.h>
#include <TVector3.h>
#include <TObject.h>
#include <TH1D.h>
#include <TNamed.h>
#include <TTree.h>
#include "TNtHisto.h"

class TNtHisto1D : public TNtHisto {


private:

  TH1D *fH_;



public:


 TNtHisto1D (const char *hname);
 TNtHisto1D (const char *hname,int bins, double low, double hi);
~TNtHisto1D ();

 void       SetBins(int nx, double xmin, double xmax, int ny = 0, double ymin = 0., double ymax=0.);
 //________ Set Internal Variables _________________________________________

 void  SetTitle(const char *title, const char *ytit="")     {   fH_->SetXTitle(title);
   fH_->SetYTitle(ytit);};

 //________ Get Internal Variables __________________________________________

 int        GetDim() { return 1;};
 TString    GetHistName();
 TObject    *GetH()         {   return (TObject *) fH_;};
 void       Fill(TTree *tree, const char *opt = "goff");
 void       Print();

 ClassDef(TNtHisto1D,1)

};
#endif
