c  cltmed.inc

c  $Id: cltmed.inc,v 1.11 2004/08/20 18:01:32 clarisse Exp $

      character*132 cicltmed
      data cicltmed/
     1'$Id: cltmed.inc,v 1.11 2004/08/20 18:01:32 clarisse Exp $'
     1/

	integer clas_med_air,clas_med_helium,clas_med_mylar,
     1       clas_med_carbon,clas_med_vac,
     1       clas_med_beryl, clas_med_alu, 
     1       clas_med_lead , clas_med_copper, clas_med_h2liq,
     1       clas_med_iron , clas_med_ch2,
     1        clas_med_helium4,clas_med_d2liq,clas_med_alumylar,
     1       clas_med_roha,clas_med_kapton,clas_med_cerexmyl1,
     1       clas_med_lowdfoam,clas_med_alumaseal,clas_med_cfiber,
     1       clas_med_cerex,clas_med_titanium,clas_med_rigidgraphite,
     1       clas_med_flexgraphite
      
	common/cltmed/clas_med_air,clas_med_helium,clas_med_mylar,
     1       clas_med_carbon,clas_med_vac,
     1       clas_med_beryl, clas_med_alu, 
     1       clas_med_lead , clas_med_copper, clas_med_h2liq,
     1       clas_med_iron , clas_med_ch2,
     1       clas_med_helium4,clas_med_d2liq,clas_med_alumylar,
     1       clas_med_roha,clas_med_kapton,clas_med_cerexmyl1,
     1       clas_med_lowdfoam,clas_med_alumaseal,clas_med_cfiber,
     1       clas_med_cerex,clas_med_titanium ,clas_med_rigidgraphite,
     1       clas_med_flexgraphite   
     
     
