
       REAL ewsa(48)
       REAL es11r(48),es11i(48)
       REAL es31r(48),es31i(48)
       REAL ep11r(48),ep11i(48)
       REAL ep13r(48),ep13i(48)
       REAL ep31r(48),ep31i(48)
       REAL ep33r(48),ep33i(48)
       REAL ed13r(48),ed13i(48)
       REAL ed15r(48),ed15i(48)
       REAL ed33r(48),ed33i(48)
       REAL ef15r(48),ef15i(48)
       REAL ef37r(48),ef37i(48)
       REAL ef17r(48),ef17i(48)
       REAL ef35r(48),ef35i(48)
       common/ebac/ 
     +      es11r,es11i,es31r,es31i,
     +      ep11r,ep11i,ep13r,ep13i,ep31r,ep31i,ep33r,ep33i,
     +      ed13r,ed13i,ed15r,ed15i,ed33r,ed33i,
     +      ef15r,ef15i,ef17r,ef17i,ef35r,ef35i,
     +      ef37r,ef37i,ewsa





