C-
      REAL FUNCTION rf_tof_cal()
C-      
*********************************************************
*                                                       *
* This file was generated by HUWFUN.                    *
*                                                       *
*********************************************************
*
*     Ntuple Id:      10   
*     Ntuple Title:   CLAS
*     Creation:       20/12/97 14.54.03
*
*********************************************************
*	
	include ?
*
*--   Enter user code here
*
C-
	parameter ( CalConst_RF  = 1.000 )
	parameter ( CalConst_TOF = 1.000 )
	parameter ( RF_Period = 2.004 )	
C-
	character*6 VarName(5) 
	data VarName /        'Sect' , 'Strp',
     &	                      'D_T','Type', 'CT' /	
     	real XNtuple(5)
C-
	real E_b, M_n, M_pi
	parameter ( M_n = 0.938 )
	parameter ( M_pi = 0.1396 )
C
	logical FirstTime
	logical TBT 
	data FirstTime / .TRUE. /
C
	real E_dep_e, E_dep_h
	real TDC_e, TOF_e, TDC_h, TOF_h, TOF_h_t
	real Mass_h, Beta_h, Path_h, Mass_h2_t
	real iSect_e, iSect_h
	real iStrip_e, iStrip_h
	real DeltaT, CT
	real DE_DX_CUT_PR, DE_DX_CUT_PI, DE_DX_CUT_EL
C-
	vector E_BM(1)	
C-
	if ( FirstTime ) then
	 E_b = E_BM(1)
	 write(6,*)'Booking Histograms...'
c	 call HROPEN(27,'GS','temp.hbook','N',4096,iStat)
	 if ( .NOT.HEXIST(20) ) then
	  call HBOOKN(20, 'NTUPLE', 5, '//LUN44',1000, VarName)
	 endif
	 call HBOOK2(600,'DE_DX',50, 0., E_b, 50,0., 50., 0.)
	 call HBOOK1(610,'DT e',300, +0., +300, 0.)
	 call HBOOK1(620,'CT e',300, -3., +3., 0.)	
	 call HBOOK2(630,'Strp_h Vs Strp_e', 25, 0.5, 25.2,
     &	    48, 0.5, 48.5, 0. )	
     	 call HBOOK1(670, 'Mass Test', 100, 0. , 1.5 , 0. )
         call HBOOK2(720 , 'CT vs DT ', 200., 60., 
     &      260.4 , 50. , -1. , 1., 0. )
	 call HBOOK1(640,'DT [p]',1000, +60., +260., 0.)
	 call HBOOK1(650,'CT [p]',300, -3., +3., 0.)	  
     	 write(6,*) 'Booking Done . '
	endif
	FirstTime = .FALSE.
	TBT = .FALSE.
C-
	if ( (gpart .GE. 1) .and. ( dc(1) .EQ. 0. ) ) then
	 tof_cal = 1.
         return	
     	endif	
C-     	
	if ( (gpart .GE. 1) .and. (id(1) .EQ. 11) .and. 
     &	     (dc_stat(dc(1)) .GT. 0.1 ) .and.	 
     &	     (p(1) .GT. 0.01) .and. 
     &	     (p(1) .LT. E_b ) .and. 
     & 	     (sc(1) .GT. 0)  .and. 
     &       (q(1) .LT. 0.) 
c     &	     .and. rf_time1 .GT. 35. 
c     &	     .and. rf_time1 .LT. 168.
     &	     ) then 
C-
C-	 It is an electron that has a hit in SC
C-
	 iSect_e = sc_sect( sc(1) )
	 iStrip_e = sc_pd( sc(1) ) 
	 E_Dep_e = edep( sc(1) )
	 TDC_e = sc_t( sc(1) ) * CalConst_TOF
	 Path_e = sc_r( sc(1) )	 
	 TOF_e = Path_e / 30.
	 DeltaT = ( TDC_e - TOF_e ) - rf_time1*CalConst_RF
     +	  +100.*RF_Period
	 CT = AMOD(DeltaT,Rf_Period)-RF_Period/2.
C	 
	 XNtuple(1) = iSect_e
	 XNtuple(2) = iStrip_e	 
	 XNtuple(3) = DeltaT
	 XNtuple(4) = 3.
	 XNTuple(5) = CT
	 call HFN(20, XNtuple)
	if ( iSect_e .EQ. 1 .AND. iStrip_e .EQ. 4 ) then	 
	 call HF1(610, DeltaT, 1.)
	 call HF1(620, CT, 1. )
         call HF2(720, DeltaT, CT, 1.)
	endif 
C-
	 do iPrt = 2, gpart
	  if ( dc(iPrt) .EQ. 0. ) then 
	   TBT = .FALSE.
	  else
	   TBT = .TRUE. 
	  endif
	  if ( sc(iPrt) .GT. 0 .and.
     &	      TBT .and. 
     &        p(iPrt) .GT. 0.01 .and. 
     &        p(iPrt) .LT. E_b  
c     &	      .and. q(iPrt) .GT. 0. 
     &	       ) then
C-	  
	   Type = 0  
	   E_Dep_h = edep( sc(iPrt) )
	   TDC_h = sc_t( sc(iPrt) ) * CalConst_TOF
	   Path_h = sc_r( sc(iPrt) )  
	   TOF_h_t = TDC_h  -
     - 	       ( TDC_e - TOF_e )
     	   Mass_h2_t = p(iPrt)**2*( ( 30.0 * TOF_h_t 
     /	     / Path_h )**2-1.) 
     	   call HF1( 670 , Mass_h2_t, 1. )
        
C-	   
	   call HF2(600, p(iPrt), E_Dep_h, 1.)	
C-	   	   
	   if (     E_Dep_h .GT. DE_DX_CUT_PR(p(iPrt)) 		
     &	      .and. E_Dep_h .GT. DE_DX_CUT_EL(p(iPrt))
c     &	      .and. Mass_h2_t .GT. 0.7**2 
     &	        ) then    
	    Beta_h = 1. / Sqrt(1. + (M_n/p(iPrt))**2 )   
	    Type = 1
	   elseif ( E_Dep_h .LT. DE_DX_CUT_PI(p(iPrt)) 
     &	      .and. E_Dep_h .GT. DE_DX_CUT_EL(p(iPrt))	
c     &	      .and. Mass_h2_t .LT. 0.3**2   
     &	       ) then  
	    Beta_h = 1. / Sqrt(1. + (M_pi/p(iPrt))**2 )   
	    Type = 2  
	   endif 
	   if ( Type .GT. 1 ) then 
	    iSect_h = sc_sect( sc(iPrt) )
	    iStrip_h = sc_pd( sc(iPrt) ) 
  	    TOF_h = ( Path_h / Beta_h ) / 30.
	    DeltaT = ( TDC_h - TOF_h ) - rf_time1*CalConst_RF
     +	     +100.*RF_Period
	    CT = AMOD(DeltaT,RF_Period)-RF_Period/2.	
            if ( iStrip_h .EQ. 22 .and. iSect_h .EQ. 1 ) then
	     call HF1(640, DeltaT, 1.)
	     call HF1(650, CT, 1. )
            endif

C-
	    XNtuple(1) = iSect_h
	    XNtuple(2) = iStrip_h
	    XNtuple(3) = DeltaT
	    XNtuple(4) = Type
	    XNtuple(5) = CT
	    call HFN(20, XNtuple)
	   endif	   	   
C-	  
	  endif
	 enddo
C-	 


C-
	endif
	
C-	
	rf_tof_cal =1.
	return 
*
      END
C=================================================================
	real function DE_DX_CUT_PR(X)
	 DE_DX_CUT_PR = 19.7547-7.058824*X	
	return
	end  
C==================================================================
	real function DE_DX_CUT_PI(X)
	 DE_DX_CUT_PI = 17.-6.*X	
	return
	end  
C==================================================================
	real function DE_DX_CUT_EL(X)
	 DE_DX_CUT_EL = 6.0 - 0.*X	
	return
	end  
	
	
	    
