#! gnumake

#---------------------------------------------------
# The D. P. Weygand Makefile
#---------------------------------------------------

include $(CLAS_CMS)/rules.make
include $(CLAS_CMS)/Rules.make

ifdef USEBOSIO
BOSLIB= -lbosio$(ADD_DEBUG)
else
BOSLIB = -lfputil$(ADD_DEBUG) -lbos$(ADD_DEBUG) -lfpack$(ADD_DEBUG)
endif

STDLIBS= -L$(TOP_DIR)/lib/$(OS_NAME) -L$(CLAS_LIB) -lsc$(ADD_DEBUG) -lc_cern$(ADD_DEBUG) -lpid -lc_bos_io$(ADD_DEBUG) \
-lec$(ADD_DEBUG) -lcc$(ADD_DEBUG) -lrecutl$(ADD_DEBUG) -lclasutil$(ADD_DEBUG) -lonline_dummy -lfputil$(ADD_DEBUG) -lbos$(ADD_DEBUG)       \
-lfpack$(ADD_DEBUG) -lc_bos_io$(ADD_DEBUG) -lst 

INCLUDE += -I$(MYSQL_INCLUDE_PATH)

ifndef MAP
STDLIBS += -lcaldbMap$(ADD_DEBUG) -lclasutil$(ADD_DEBUG) -L$(MYSQL_LIB_PATH) -lmysqlclient  -ldl
else
STDLIBS += -lmapmanager$(ADD_DEBUG)	
endif

OTHER  = /usr/local/lib
ifeq "$(OS_NAME)" "LinuxRH6"
STDLIBS +=  -lz  -ltcl
endif
ifeq "$(OS_NAME)" "LinuxRH7"
STDLIBS +=  -lz  -ltcl
endif
ifeq "$(OS_NAME)" "LinuxRHEL3"
STDLIBS +=  -lz -L$(OTHER2)/-ltcl8
endif
ifeq "$(OS_NAME)" "SunOS"
STDLIBS += -lsocket -lnsl -L/usr/lib -ltcl 
endif	

#use the newest cern library
CERNPATH=  $(CERN_ROOT)/lib
CERNLIB= -L$(CERNPATH) -lpacklib 
MATHLIB= -lm

FINCLUDE := $(FINCLUDE) -I./include
INCLUDE  := $(INCLUDE)  -I./include

MISCLIB_SunOS :=  -L/usr/lib -lm -lc -lnsl -lsocket
MISCLIB_HP-UX :=  -L/usr/lib -lm -lc -lf
MISCLIB_AIX   :=  -L/usr/lib -lxlf90 -lm -lc 
MISCLIB_Linux :=  -L/usr/lib  -lm -lc /usr/lib/libf2c.a

MISCLIB := $(MISCLIB_$(OS_NAME))

LIBS  = $(STDLIBS) $(BOSLIBS) $(CERNLIB) $(FLIB) $(MISCLIB) $(MATHLIB) $(STDLIBS)
LIBS2 = $(STDLIBS) $(BOSLIBS) $(CERNLIB) $(FLIB) $(MISCLIB) $(STDLIBS)

make_tw_histos: make_tw_histos.o
	$(CC) -o $@ make_tw_histos.o $(LIBS2)	

min_main: min_main.o min_walk.o
	$(F77) -o $@ min_main.o min_walk.o $(LIBS)

hscan: hscan.o 
	$(F77) -o $@ hscan.o $(LIBS)

ALL = make_tw_histos hscan min_main


all: $(ALL)

env:
	@echo CC $(CC)
	@echo F77 $(F77)
	@echo INCLUDE $(INCLUDE)
	@echo BOSPATH $(BOSPATH)
	@echo FLIB $(FLIB)
	@echo LIBS $(LIBS)
	@echo CERNLIB\\t$(CERNLIB)







