// Autogenerated Class (Header File)
// Author : G.Gavalian
// Date   : Tue Mar 27 13:21:19 EST 2007
//

#ifndef __TCTParticle__
#define __TCTParticle__
#include <iostream>
#include <TROOT.h>
#include <TVector3.h>
#include <TObject.h>
#include <TLorentzVector.h>
#include <TEVNTClass.h>
#include <TVirtualReader.h>

class TCTParticle : public TNamed{

private:

  TString   fPartName;
  Int_t     fPartType;
  Int_t     fPartState;
  Int_t     fExclusiveFlag;
  Double_t  fPartMass;
  Double_t  fPartDOCA;


  TEVNTClass      fPARTBank;
  TVector3        fPart3vector;
  TLorentzVector  fPartLorentzVector;
  TVector3        fPartVertex;
  Int_t           fPartStatus;

public:


  TCTParticle (const char *name);
  TCTParticle (const char *name,int type,double mass);

  

  ~TCTParticle ();
 
  void   ResetPart();
  Int_t  GetStatus(){return fPartStatus;};
  void   SetDOCA(double __doca){fPartDOCA = __doca;};
  void   SetVector(TLorentzVector __v1){fPartLorentzVector = __v1;};
  void   SetVertex(TVector3 __vrt){fPartVertex = __vrt;};
  void   SetPartType(int type){fPartType = type;};
  int    SetPart(TEVNTClass *ptr);
  int    SetParticle(TVirtualReader *fR, int idx);
  void   SetMass(double m ){fPartMass = m;};
  int    Status(){return fPartStatus;};
  void   SetStatus(int __st){fPartStatus = __st;};
  //  void   Reset(){fPartState = 0;};
  
  Double_t        Get(const char *var);
  Int_t           GetType(){return fPartType;};
  Double_t        GetMass(){return fPartMass;};
  
  TLorentzVector  GetV();
  TVector3        GetVert(){return fPartVertex;};

  ClassDef(TCTParticle,1)
};
#endif
