// Autogenerated Class (Source File)
// Author : G.Gavalian
// Date   : Fri Nov 30 14:47:15 EST 2007
//

#include "TCTParticleList.h"



ClassImp(TCTParticleList)


TCTParticleList::TCTParticleList (TGCanvas* p, UInt_t options, Pixel_t back): 
    TGListTree(p,options,back)
{
  Init();
}

TCTParticleList::~TCTParticleList (){

}
//-----------------
//-----------------
//-----------------
void   TCTParticleList::Init()
{
  fgListParticles = AddItem(0,"Particles");
  //  AddItem(fgListParticles,"beam");
  //  AddItem(fgListParticles,"target");
  fgListComposite = AddItem(0,"Composite");
  fgListVectors   = AddItem(0,"Vectors");
  fgListVariables = AddItem(0,"Variables");
  //  AddItem(fgListVariables,"ebeam");
  //  AddItem(fgListVariables,"btime");
  //  AddItem(fgListVariables,"runnum");
  //  AddItem(fgListVariables,"evtnum");
  OpenItem(fgListParticles);
  OpenItem(fgListComposite);
  OpenItem(fgListVectors);
  OpenItem(fgListVariables);
}
void     TCTParticleList::FillFromContainer(TCTContainer *_fct)
{
  int      n_ent;
  TString  el_name;
  DeleteChildren(fgListParticles);
  DeleteChildren(fgListComposite);
  DeleteChildren(fgListVectors);
  DeleteChildren(fgListVariables);

  n_ent = _fct->GetNElements("Particles");
  for(int i=0;i<n_ent;i++){
    el_name = _fct->GetElementName("Particles",i);
    AddItem(fgListParticles,el_name.Data());
  }

  n_ent = _fct->GetNElements("Composite");
  for(int i=0;i<n_ent;i++){
    el_name = _fct->GetElementName("Composite",i);
    AddItem(fgListComposite,el_name.Data());
  }

  n_ent = _fct->GetNElements("Vectors");
  for(int i=0;i<n_ent;i++){
    el_name = _fct->GetElementName("Vectors",i);
    AddItem(fgListVectors,el_name.Data());
  }

  n_ent = _fct->GetNElements("Variables");
  for(int i=0;i<n_ent;i++){
    el_name = _fct->GetElementName("Variables",i);
    AddItem(fgListVariables,el_name.Data());
  }
  
}

void   TCTParticleList::AddParticle(const char *name, const char *type)
{
  AddItem(fgListParticles,name);
}

TString TCTParticleList::GetSelectedName()
{
  TGListTreeItem *_ptr = GetSelected();
  if(_ptr==NULL) return TString("NONE");
  return TString(_ptr->GetText());
}
Int_t   TCTParticleList::GetNPart()
{
  TGListTreeItem *_achild = fgListParticles->GetFirstChild();
  if(_achild==NULL) return 0;
  Int_t  iN = 1;
  while((_achild = _achild->GetNextSibling())!=NULL) iN++;
  return iN;
}
