// Autogenerated Class (Source File)
// Author : G.Gavalian
// Date   : Wed Jan  9 13:12:06 EST 2008
//

#include "TCTVirtualParticleCorrections.h"



ClassImp(TCTVirtualParticleCorrections)


TCTVirtualParticleCorrections::TCTVirtualParticleCorrections (){

}

TCTVirtualParticleCorrections::~TCTVirtualParticleCorrections (){

}


//-----------------
//-----------------
//-----------------
TLorentzVector  TCTVirtualParticleCorrections::GetBeamVector(TLorentzVector fvBeam, Int_t _pdg_id)
{
	printf("VirtualParticleCorrections:: This is virtual function and you shouldn't be using this\n");
	TLorentzVector  vV(0.,0.,0.,0.);
	return vV;
}
TLorentzVector  TCTVirtualParticleCorrections::GetParticleVector(TLorentzVector fvPart, Int_t _pdg_id)
{
	printf("VirtualParticleCorrections:: This is virtual function and you shouldn't be using this\n");
	TLorentzVector  vV(0.,0.,0.,0.);
	return vV;
}

TLorentzVector  TCTVirtualParticleCorrections::GetParticleVector(TLorentzVector fvPart, const char *_pdg_name)
{
	printf("VirtualParticleCorrections:: This is virtual function and you shouldn't be using this\n");
	TLorentzVector  vV(0.,0.,0.,0.);
	return vV;
}
