// Autogenerated Class (Header File)
// Author : G.Gavalian
// Date   : Wed Jan  9 13:12:06 EST 2008
//

#ifndef __TCTVirtualParticleCorrections__
#define __TCTVirtualParticleCorrections__
#include <iostream>
#include <TROOT.h>
#include <TVector3.h>
#include <TObject.h>
#include <TLorentzVector.h>

class TCTVirtualParticleCorrections : public TObject {
private:

public:

TCTVirtualParticleCorrections ();
~TCTVirtualParticleCorrections ();


virtual   TLorentzVector  GetBeamVector(TLorentzVector fvBeam, Int_t _pdg_id=11);
virtual   TLorentzVector  GetParticleVector(TLorentzVector fvPart, Int_t _pdg_id);
virtual   TLorentzVector  GetParticleVector(TLorentzVector fvPart, const char *_pdg_name);

ClassDef(TCTVirtualParticleCorrections,1)

};
#endif
