// Autogenerated Class (Header File)
// Author : G.Gavalian
// Date   : Fri Mar 30 12:56:52 EST 2007
//

#ifndef __TFrameTabView__
#define __TFrameTabView__
#include <iostream>
#include <TROOT.h>
#include <TVector3.h>
#include <TObject.h>
#include <TCanvas.h>
#include <TGProgressBar.h>
#ifndef ROOT_TGFrame
#include "TGFrame.h"
#endif

#ifndef ROOT_TGButton
#include "TGButton.h"
#endif

#ifndef ROOT_TGTextEntry
#include "TGTextEntry.h"
#endif

#ifndef ROOT_TGListBox
#include <TGListBox.h>
#endif

#ifndef ROOT_TGTab
#include <TGTab.h>
#endif
#include <TGButton.h>
//#include "TNtUtils.h"
#include <TRootEmbeddedCanvas.h>
#include <TGTextEdit.h>
#include <TGLabel.h>

class TFrameTabView :  public TGCompositeFrame {

private:
    TGTab                *fDisplayFrame;
    TRootEmbeddedCanvas  *fEmbeddedCanvas;
    TGLayoutHints        *fL1;
    TGLayoutHints        *fL2;
    TGTextEdit           *fTextView;
    TGHProgressBar       *fProgress;
    TGVerticalFrame *fHframe1;
public:

TFrameTabView (const TGWindow* p);

virtual ~TFrameTabView ();


 void    AddMessage(const char *mess);
 void    ActiveTab(int i){fDisplayFrame->SetTab(i);};
 void    ActivateCanvas();
 TGProgressBar  *GetProgressBar(){ return (TGProgressBar *) fProgress;};
 void    UpdateCanvas();
 void    PrintCanvas(const char *fname);
 void    SetStyles();

ClassDef(TFrameTabView,1)


};
#endif
