// Autogenerated Class (Source File)
// Author : G.Gavalian
// Date   : Fri Mar 30 14:33:33 EST 2007
//

#include "TFrameTitle.h"



ClassImp(TFrameTitle)


TFrameTitle::TFrameTitle (const TGWindow *p,
              const Text_t *mainText)
  : TGCompositeFrame(p, 100,80, kSunkenFrame)
{
  const TGFont *font = fClient->GetFont("-*-times-bold-r-*-*-24-*-*-*-*-*-*-*");
  if (!font)
    font = fClient->GetResourcePool()->GetDefaultFont();

  FontStruct_t labelfont = font->GetFontStruct();
  GCValues_t   gval;
  gval.fMask = kGCForeground | kGCFont;
  gval.fFont = font->GetFontHandle();
  gClient->GetColorByName("blue", gval.fForeground);
  fTextGC.SetAttributes(&gval);

  fTextLabel1 = new TGLabel(this,mainText, fTextGC(), labelfont);
  AddFrame(fTextLabel1,new TGLayoutHints(kLHintsTop | kLHintsExpandX, 10, 10, 10, 10));

}

TFrameTitle::~TFrameTitle (){

}

//-----------------
//-----------------
//-----------------
