// Autogenerated Class (Source File)
// Author : G.Gavalian
// Date   : Fri Mar 30 12:56:52 EST 2007
//

#include "TFrameTabView.h"
#include "TStyle.h"


ClassImp(TFrameTabView)


TFrameTabView::TFrameTabView (const TGWindow* p):
  TGCompositeFrame(p, 580, 360, kVerticalFrame | kRaisedFrame)
{

  SetStyles();
  gStyle->SetOptFit(11111);
  fL1 = new TGLayoutHints(kLHintsTop | kLHintsLeft | kLHintsExpandX | kLHintsExpandY,
			  2, 2, 2, 2);
  fL2 = new TGLayoutHints(kLHintsTop | kLHintsLeft | kLHintsExpandX ,
			  5, 5, 5, 5);
  fDisplayFrame = new TGTab(p, 580, 360);
  TGCompositeFrame *tFrame_1 = fDisplayFrame->AddTab("Display");
  TGCompositeFrame *tFrame_2 = fDisplayFrame->AddTab("Messages");
  TGCompositeFrame *tFrame_3 = fDisplayFrame->AddTab("Scetch Board");
  fEmbeddedCanvas = new TRootEmbeddedCanvas("fEmbeddedCanvas", tFrame_1, 580, 600);
  fEmbeddedCanvas->GetCanvas()->SetFrameFillColor(10);
  tFrame_1->AddFrame(fEmbeddedCanvas,fL1);
  fTextView = new TGTextEdit(tFrame_2, 300, 100, kSunkenFrame | kDoubleBorder);
  tFrame_2->AddFrame(fTextView, fL1);
  fHframe1 = new TGVerticalFrame(tFrame_3, 0, 0, 0);

  fProgress = new TGHProgressBar(fHframe1,TGProgressBar::kFancy,300);
  fHframe1->AddFrame(new TGLabel(fHframe1,"Progress of The Job"),fL2);
  fHframe1->AddFrame(new TGLabel(fHframe1,"Please, Make some Coffee and wait......"),fL2);
  fHframe1->AddFrame(fProgress,fL2);
  tFrame_3->AddFrame(fHframe1,fL2);
  AddFrame(fDisplayFrame,fL1);
}

TFrameTabView::~TFrameTabView (){
  delete fDisplayFrame;
}

//-----------------
//-----------------
//-----------------
void    TFrameTabView::AddMessage(const char *mess)
{
  ActiveTab(1);
  fTextView->AddLine(mess);
}

void    TFrameTabView::ActivateCanvas()
{
  ActiveTab(0);
  gStyle->SetOptStat(1111111);
  fEmbeddedCanvas->GetCanvas()->cd();
}

void    TFrameTabView::UpdateCanvas()
{
  ActiveTab(0);
  fEmbeddedCanvas->GetCanvas()->Modified();
  fEmbeddedCanvas->GetCanvas()->Update();  
}

void    TFrameTabView::PrintCanvas(const char *fname)
{
  fEmbeddedCanvas->GetCanvas()->Print(fname);
}

void    TFrameTabView::SetStyles()
{
  TStyle *fS = gStyle;
  fS->SetPadColor(10);
  fS->SetPadBottomMargin(0.2);
  fS->SetPadLeftMargin(0.24);
  fS->SetPadTopMargin(0.05);
  fS->SetPadRightMargin(0.07);
  fS->SetCanvasColor(10);
  fS->SetStatBorderSize(1);
  fS->SetStatColor(10);
  fS->SetOptFit(1111);
  fS->SetStatW(0.2);
  fS->SetStatH(0.1);
  fS->SetStatX(0.99-0.07);
  fS->SetStatY(0.99-0.045);
  fS->SetFrameLineWidth(2);
}
