// Autogenerated Class (Header File)
// Author : G.Gavalian
// Date   : Wed Jun 27 18:02:49 EDT 2007
//

#ifndef __TNtHisto2D__
#define __TNtHisto2D__
#include <iostream>
#include <TROOT.h>
#include <TVector3.h>
#include <TObject.h>
#include "TNtHisto.h"
#include <TH2D.h>
#include <TTree.h>
#include <TString.h>

class TNtHisto2D : public TNtHisto {

private:

  TH2D *fH_;

public:

TNtHisto2D (const char *hname);
~TNtHisto2D ();

 void       SetBins(int nx, double xmin, double xmax, int ny = 0, double ymin = 0., double ymax=0.);
 //________ Set Internal Variables _________________________________________

 void  SetTitle(const char *title, const char *ytit="")     {   fH_->SetXTitle(title);
   fH_->SetYTitle(ytit);};

 int        GetDim() { return 2;};
 TString    GetHistName();
 TObject    *GetH()         {   return (TObject *) fH_;};
 void       Fill(TTree *tree, const char *opt = "goff");
 // void       Print();


 ClassDef(TNtHisto2D,1)

};
#endif
