#!/bin/sh

if [ `uname` = Linux ]; then
#
#     OS is Linux; there are dependencies related 
#     to the RedHat 5.x, debian distribution, so we need to be
#     more specific
#
  if [ -f /etc/redhat-release ]; then
    echo RedHat
  fi
  if  [ -f /etc/debian_version ]; then
    echo Debian
  fi
  if [ -d /etc/SuSEconfig ]; then
    echo SuSE
  fi
         
fi
