       REAL BM3,BE3,BS3
       REAL BM1,BE1,BS1
       REAL BbM3,BbE3,BbS3
       REAL BbM1,BbE1,BbS1
       REAL RM3,RE3,RS3
       REAL RM1,RE1,RS1
       REAL E0,M1,S0,S1


	COMMON/BACK_AMPL/BM3(8),BE3(8),BS3(8),
     +      BM1(2,9),BE1(2,9),BS1(2,9),
     +      BbM3(8),BbE3(8),BbS3(8),
     +      BbM1(2,9),BbE1(2,9),BbS1(2,9),
     +      RM3(8),RE3(8),RS3(8),
     +      RM1(2,9),RE1(2,9),RS1(2,9),
     +      E0(2),M1(2),S0(2),S1(2)




